name: Terraform deploy

on:
  workflow_dispatch:
env:
  tf_version: "~> 1.14"
  aws_region: "us-east-1"

jobs:
  tf_apply:
    name: Apply
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: |
          terraform plan \
            -var-file="envs/${{ github.ref_name }}.tfvars" \
            -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan